name: create-release
on:
  workflow_call:
    inputs:
      bump:
        description: "The bump in version for this release, either 'major', 'minor' or 'patch'"
        required: true
        type: string
        default: 'patch'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      ref: v${{ steps.bump-version.outputs.version }}
      version: ${{ steps.bump-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extracting version from properties
        shell: bash
        run: echo "version=$(cat gradle.properties | grep -w "mod_version" | cut -d= -f2)" >> $GITHUB_OUTPUT
        id: extract-version
      - name: Bumping version
        uses: TwelveIterationMods/bump-version@v1
        with:
          version: ${{ steps.extract-version.outputs.version }}
          bump: ${{ inputs.bump }}
        id: bump-version
      - name: Updating version properties
        run: |
          sed -i "s/^\s*mod_version\s*=.*/mod_version = ${{ steps.bump-version.outputs.version }}/g" gradle.properties
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git commit -am "Set version to ${{ steps.bump-version.outputs.version }}"
          git push origin ${BRANCH_NAME}
          git tag -a "v${{ steps.bump-version.outputs.version }}" -m "Release ${{ steps.bump-version.outputs.version }}"
          git push origin "v${{ steps.bump-version.outputs.version }}"
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  publish-release:
    uses: TwelveIterationMods/Workflows/.github/workflows/publish-release.yml@main
    with:
      ref: ${{ needs.create-release.outputs.ref }}
      version: ${{ needs.create-release.outputs.version }}
    secrets: inherit
    needs: create-release