name: publish-release
on:
  workflow_call:
    inputs:
      ref:
        description: "The ref to publish a release for"
        type: string
      version:
        description: "The version to publish a release as"
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        loader: [ shared, fabric, forge, neoforge ]
        site: [ curseforge, modrinth, publish ]
        exclude:
          - loader: shared
            site: curseforge
          - loader: shared
            site: modrinth
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish
        run: ./gradlew :${{ matrix.loader }}:${{ matrix.site }} '-Pmod_version=${{inputs.version}}' '-PtwelveIterationsNexusUsername=${{ secrets.NEXUS_USER }}' '-PtwelveIterationsNexusPassword=${{ secrets.NEXUS_PASSWORD }}'
        env:
          CURSEFORGE_TOKEN: ${{secrets.CURSEFORGE_TOKEN}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}
