name: publish-snapshot
on: [workflow_call]

jobs:
  publish-snapshot-fabric:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Restore build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Artifacts
          path: fabric/build/libs/
      - name: Publish
        run: ./gradlew :fabric:publish
        env:
          GPR_USERNAME: ${{secrets.GPR_USERNAME}}
          GPR_TOKEN: ${{secrets.GPR_TOKEN}}
          GPR_BUILD_NUMBER: ${{github.run_number}}
  publish-snapshot-forge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Restore build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Artifacts
          path: forge/build/libs/
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish
        run: ./gradlew :forge:publish
        env:
          GPR_USERNAME: ${{secrets.GPR_USERNAME}}
          GPR_TOKEN: ${{secrets.GPR_TOKEN}}
          GPR_BUILD_NUMBER: ${{github.run_number}}