name: publish-snapshot
on: [workflow_call]

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        loader: [fabric, forge]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish
        run: ./gradlew :${{ matrix.loader }}:publish '-Pmod_version=${{ github.sha }}-SNAPSHOT' '-PtwelveIterationsNexusUsername=${{ secrets.NEXUS_USER }}' '-PtwelveIterationsNexusPassword=${{ secrets.NEXUS_PASSWORD }}'
