name: publish-release
on:
  workflow_call:
    inputs:
      ref:
        description: "The ref to publish a release for"
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        loader: [fabric, forge]
        site: [curseforge, modrinth]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Extract version from tag
        shell: bash
        run: echo "version=$(echo ${GITHUB_REF#refs/*/v})" >> $GITHUB_OUTPUT
        id: extract_version
      - name: Publish
        run: ./gradlew :${{ matrix.loader }}:publish :${{ matrix.loader }}:${{ matrix.site }}
        env:
          GPR_USERNAME: ${{secrets.GPR_USERNAME}}
          GPR_TOKEN: ${{secrets.GPR_TOKEN}}
          CURSEFORGE_TOKEN: ${{secrets.CURSEFORGE_TOKEN}}
          MODRINTH_TOKEN: ${{secrets.MODRINTH_TOKEN}}
          GPR_BUILD_VERSION: ${{steps.extract_version.outputs.version}}
